### PR TITLE
Add linting for Mocha

### PR DESCRIPTION
**Pull request by paulmelnikow**
Hoping to get `no-mocha-global-arrows` pulled in upstream: lo1tuma/eslint-plugin-mocha#78.

Meanwhile, seems like we could pull this in here.

The main value is linting arrows in mocha, which should reduce the need to comment on it in PR comments, and also make conversion faster, since you'll see the problems right away.

Other two options are nice-to-haves:

- missing `done` callbacks
- we don't tend to use `it` outside `describe`, so enforce that.

### CODE REVIEW

**Comment by gmarceau** [comment]
nice! 👍

**Comment by maxdumas** [comment]
Forgetting to handle `done` is a mistake I frequently make when refactoring tests, so this is awesome! 👍

**Comment by paulmelnikow** [comment]
@dlsmith

**Comment by dlsmith** [comment]
👍

**Comment by paulmelnikow** [comment]
Thanks

**Pull request merged**
